/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { JobPosts } from './jobPosts';


export interface User { 
    email: string;
    favorites?: Array<JobPosts>;
    id?: number;
    name: string;
    password: string;
    previousApplications?: Array<JobPosts>;
    resume?: string;
    surname: string;
}
